import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const text = async (path) =>
  (await readFile(join(root, path), "utf8")).replaceAll("\r\n", "\n");
const json = async (path) => JSON.parse(await text(path));
const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const lock = await json("package-lock.json");
const manifest = await json("docs/licenses/runtime/sources.json");
const pyodide = await json("node_modules/pyodide/package.json");
const runtime = await json("node_modules/pyodide/pyodide-lock.json");
// These development packages inject JavaScript into the production browser
// bundle (module-preload and CommonJS/ESM interoperability helpers).
const emittedHelpers = new Set(["node_modules/vite", "node_modules/rolldown"]);
if (
  pyodide.version !== manifest.pyodide ||
  runtime.info.python !== manifest.python ||
  runtime.info.platform !== manifest.platform
) {
  throw new Error(
    "Python runtime versions changed. Review and update docs/licenses/runtime/sources.json and its upstream notices before generating a release.",
  );
}

const notices = [
  "TRACEPAD THIRD-PARTY NOTICES",
  "Generated by scripts/generate-notices.mjs. Do not edit this file directly.",
  "Scope: production npm dependency closure in package-lock.json, optional platform variants, Vite/Rolldown emitted browser helpers, and pinned Python runtime notices.",
  "License expressions are upstream declarations, not a replacement for the accompanying license terms.",
  "Tracepad's MIT license does not replace third-party licenses. Runtime files are copied without modification.",
  `Pyodide source: https://github.com/pyodide/pyodide/tree/${manifest.pyodide} (MPL-2.0).`,
  `CPython source: https://github.com/python/cpython/tree/v${manifest.python}.`,
  "See THIRD_PARTY_NOTICES.md in the source repository for scope and release verification notes.",
];
const packages = [];
for (const [path, entry] of Object.entries(lock.packages)
  .filter(([path, entry]) => path && (!entry.dev || emittedHelpers.has(path)))
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
  const name = path.split("node_modules/").at(-1);
  let licensePaths;
  if (name.startsWith("@esbuild/")) {
    if (
      entry.version !== lock.packages["node_modules/esbuild"].version ||
      entry.license !== "MIT"
    ) {
      throw new Error(
        `Review the platform-specific license mapping for ${name}.`,
      );
    }
    licensePaths = ["node_modules/esbuild/LICENSE.md"];
  } else if (name === "fsevents") {
    if (entry.version !== manifest.fsevents)
      throw new Error("Update the pinned fsevents notice.");
    licensePaths = ["docs/licenses/runtime/FSEVENTS-LICENSE.txt"];
  } else if (name === "pyodide") {
    if (pyodide.version !== entry.version)
      throw new Error(
        "Installed Pyodide differs from package-lock.json. Run npm ci.",
      );
    licensePaths = ["docs/licenses/runtime/PYODIDE-LICENSE.txt"];
  } else {
    const installed = await json(`${path}/package.json`);
    if (installed.version !== entry.version)
      throw new Error(
        `${name}: installed version differs from package-lock.json. Run npm ci.`,
      );
    licensePaths = (await readdir(join(root, path), { withFileTypes: true }))
      .filter(
        (file) =>
          file.isFile() &&
          /^(?:licen[sc]e|copying|notice|thirdpartynotices)(?:[._-]|$)/i.test(
            file.name,
          ),
      )
      .map((file) => `${path}/${file.name}`)
      .sort();
  }
  if (!entry.license || !licensePaths.length)
    throw new Error(
      `No license declaration or text found for ${name}; review before release.`,
    );
  const item = {
    name,
    version: entry.version,
    path,
    license: entry.license,
    scope: emittedHelpers.has(path)
      ? "emitted build helper"
      : "production dependency",
    optional: Boolean(entry.optional),
    ...(entry.os ? { os: entry.os } : {}),
    ...(entry.cpu ? { cpu: entry.cpu } : {}),
    resolved: entry.resolved,
    integrity: entry.integrity,
    notices: [],
  };
  notices.push(
    "",
    "=".repeat(72),
    `${name}@${entry.version}`,
    `Installed path: ${path}`,
    `Declared license: ${entry.license}`,
    `Package source: ${entry.resolved}`,
  );
  for (const licensePath of licensePaths) {
    const content = await text(licensePath);
    item.notices.push({ path: licensePath, sha256: sha256(content) });
    notices.push("", `--- ${licensePath} ---`, content.trimEnd());
  }
  packages.push(item);
}
for (const source of manifest.sources) {
  const content = await text(`docs/licenses/runtime/${source.file}`);
  if (sha256(content) !== source.sha256)
    throw new Error(
      `${source.file}: vendored notice hash changed; verify its upstream source before updating the manifest.`,
    );
  notices.push(
    "",
    "=".repeat(72),
    source.component,
    `Upstream source: ${source.url}`,
    `Source revision: ${source.revision}`,
    "",
    content.trimEnd(),
  );
}

const inventory = {
  schemaVersion: 1,
  scope:
    "production npm lockfile closure, Vite/Rolldown emitted browser helpers, and pinned runtime notices; other development tools are excluded",
  lockfileVersion: lock.lockfileVersion,
  runtime: {
    pyodide: manifest.pyodide,
    python: manifest.python,
    platform: manifest.platform,
    sources: manifest.sources,
  },
  packages,
};
const outputs = new Map([
  ["public/THIRD_PARTY_NOTICES.txt", `${notices.join("\n")}\n`],
  [
    "docs/licenses/npm-inventory.json",
    `${JSON.stringify(inventory, null, 2)}\n`,
  ],
]);
for (const [path, content] of outputs) {
  if (check) {
    let existing;
    try {
      existing = await text(path);
    } catch {
      /* Report the same actionable error for a missing artifact. */
    }
    if (existing !== content)
      throw new Error(
        `${path} is stale or missing. Run npm run notices and review the changes.`,
      );
  } else {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), content);
  }
}
console.log(
  `${check ? "Verified" : "Generated"} notices for ${packages.length} locked packages (including emitted build helpers) and ${manifest.sources.length} upstream notice files.`,
);
